name: clang-format Linter

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: DoozyX/clang-format-lint-action@v0.16
      with:
        source: '.'
        extensions: 'h,c,hpp,cpp'
        clangFormatVersion: 14
        inplace: True
    - uses: EndBug/add-and-commit@v9
      with:
        author_name: clang-format Bot
        author_email: clang-format@bot
        message: 'Форматирование кода (clang-format)'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
